// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRmLstme7fAg2JOpSSfA_rdlops3X8-4c',
    appId: '1:628613466295:web:488c3013be75713d766532',
    messagingSenderId: '628613466295',
    projectId: 'albuhaira-d7952',
    authDomain: 'albuhaira-d7952.firebaseapp.com',
    storageBucket: 'albuhaira-d7952.firebasestorage.app',
    measurementId: 'G-ML4JVS1ZZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr7cIKmMA-xxU4WiZVUOCVxFDzVumbYFc',
    appId: '1:628613466295:android:0a074315dac4bfd6766532',
    messagingSenderId: '628613466295',
    projectId: 'albuhaira-d7952',
    storageBucket: 'albuhaira-d7952.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-S3qJ9iM3wjIaORzhwPmyL0kVK_EUpOE',
    appId: '1:628613466295:ios:93ceac8687d0b44c766532',
    messagingSenderId: '628613466295',
    projectId: 'albuhaira-d7952',
    storageBucket: 'albuhaira-d7952.firebasestorage.app',
    iosBundleId: 'com.example.foodly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-S3qJ9iM3wjIaORzhwPmyL0kVK_EUpOE',
    appId: '1:628613466295:ios:93ceac8687d0b44c766532',
    messagingSenderId: '628613466295',
    projectId: 'albuhaira-d7952',
    storageBucket: 'albuhaira-d7952.firebasestorage.app',
    iosBundleId: 'com.example.foodly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRmLstme7fAg2JOpSSfA_rdlops3X8-4c',
    appId: '1:628613466295:web:a144d84e45b4dffc766532',
    messagingSenderId: '628613466295',
    projectId: 'albuhaira-d7952',
    authDomain: 'albuhaira-d7952.firebaseapp.com',
    storageBucket: 'albuhaira-d7952.firebasestorage.app',
    measurementId: 'G-EDQ47J4Y2P',
  );
}
